//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskHub.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

   [Table("UserProfile")]
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.TaskAssigned = new HashSet<Tasks>();
            this.TaskRequested = new HashSet<Tasks>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int UserId { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<Tasks> TaskAssigned { get; set; }
        public virtual ICollection<Tasks> TaskRequested { get; set; }
    }
}
